export const GET_CANDIDATES = 'candidates/GET_CANDIDATES';
export const SET_CANDIDATES_RANDOM_STATUSES = 'candidates/SET_CANDIDATES_RANDOM_STATUSES';
export const CONFIRM_CANDIDATES_READY_STATE = 'candidates/CONFIRM_CANDIDATES_READY_STATE';
export const MODIFY_CANDIDATE_STATUS = 'candidates/MODIFY_CANDIDATE_STATUS';

export const TOGGLE_MODAL_VISIBILITY = 'modals/TOGGLE_MODAL_VISIBILITY';
